#!/usr/bin/env bash
#create a script to install and configure HAProxy on lb-01 server and configure HAProxy to send traffic to web-01 and web-02 servers and distribute requests using a roundrobin algorithm and make sure that HAProxy can be managed via an init script and install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend muhodari-frontend
        bind *:80
        mode http
        default_backend muhodari-backend
backend muhodari-backend
        balance roundrobin
        server 6172-web-01 18.208.246.44:80 check
        server 6172-web-02 34.224.85.27:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

  echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
